name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all-features --locked
      - name: Test
        run: cargo test --all-features --locked
      - name: Lint
        run: cargo fmt -- --check && cargo clippy --all-features -- -D warnings